FaceX/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from profiles.views import home_view



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view,name="home-view"),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include("profiles.urls",namespace="profiles")),
    path('posts/', include("posts.urls",namespace="posts")),

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

profiles/urls.py
from django.urls import path
from .views import my_profile_view,invities_recived_view,profile_list_view,invite_profiles_list_view,ProfileListView,\
    send_invatation,remove_from_friends,accept_invatation,reject_invatation,ProfileDetailView

app_name="profiles"

urlpatterns = [
    path('', ProfileListView.as_view(),name="al-profiles-view"),
    path('myprofile/', my_profile_view,name="my-profile-view"),
    path('my-invities/', invities_recived_view,name="my-invities-view"),
    path('to-invite/', invite_profiles_list_view,name="invite-profiles-view"),
    path('send-invite/', send_invatation,name="send-invite-view"),
    path('remove-friend/', remove_from_friends,name="remove-friend-view"),
    path('<slug>/', ProfileDetailView.as_view(),name="profile-detail-view"),
    path('my-invities/acctept/', accept_invatation,name="accept-invite"),
    path('my-invities/reject/', reject_invatation,name="reject-invite"),

]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.shortcuts import reverse


class ProfileManager(models.Manager):

    def get_all_to_invate(self,sender):
        profiles=Profile.objects.all().exclude(user=sender) #istek gönderen kişi hariç Tüm profilleri al
        profile=Profile.objects.get(user=sender) #istek gönderen kişiyi profile değişkenine ata
        qs=Relationship.objects.filter(Q(sender=profile) | Q(reciver=profile))
        print("qs:",qs)
        print("********************")

        accepted=set([])
        for rel in qs:
            if rel.status=="accepted":
                accepted.add(rel.reciver)
                accepted.add(rel.sender)
        print(accepted)
        print("******************")

        available=[profile for profile in profiles if profile not in accepted]
        print(available)
        return available



    def get_all_profiles(self,me):
        profiles=Profile.objects.all().exclude(user=me)
        return profiles



class Profile(models.Model):
    first_name=models.CharField(max_length=100,blank=True)
    last_name=models.CharField(max_length=100,blank=True)
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    bio=models.TextField(max_length=300,default="no bio...")
    email=models.EmailField(max_length=100,blank=True)
    country=models.CharField(max_length=100,blank=True)
    avatar=models.ImageField(default="avatar.png",upload_to="avatars/")
    friends=models.ManyToManyField(User,blank=True,related_name="friends")
    slug=models.SlugField(unique=True,blank=True)
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)

    objects=ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse("profiles:profile-detail-view", kwargs={"slug": self.slug})




    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def get_post_no(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):
        return self.posts.all()


    def get_likes_given_no(self):
        likes=self.like_set.all()
        total_liked=0
        for item in likes:
            if item.value=="Like":
                total_liked+=1
        return total_liked

    def get_likes_recived_no(self):
        posts=self.posts.all()
        total_liked=0
        for item in posts:
            total_liked+=item.liked.all().count()
        return total_liked




    __initial_first_name=None
    __initial_last_name = None

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.__initial_first_name=self.first_name
        self.__initial_last_name=self.last_name



    def save(self, *args, **kwargs):
        ex = False
        to_slug=self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug=="":
            to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            while ex:
                to_slug = slugify(to_slug + " " + str(get_random_code()))
                ex = Profile.objects.filter(slug=to_slug).exists()
        else:
            to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)


STATUS_CHOICES=(
    ("send","send"),
    ("accepted","accepted")
)

class RelationshipManager(models.Manager):
    def invatations_recived(self,reciver):
        qs=Relationship.objects.filter(reciver=reciver,status="send")
        return qs


class Relationship(models.Model):
    sender=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name="sender")
    reciver=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name="reciver")
    status=models.CharField(max_length=8,choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects=RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.reciver}-{self.status}"

profiles/forms.py
from django import forms
from .models import Profile

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=("first_name","last_name","bio","avatar")

profiles/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from .models import Profile,Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView,DetailView
from django.contrib.auth.models import User
from django.db.models import Q

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin




@login_required
def home_view(request):


    user=request.user
    hello="Hello World"




    context={
        "user":user,
        "hello":hello
    }



    return  render(request,"main/home.html",context)



@login_required
def my_profile_view(request):

    profile=Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm=False

    if request.method=="POST":
        if form.is_valid():
            form.save()
            confirm=True


    context={
        "profile":profile,
        "form":form,
        "confirm":confirm
    }
    return render(request,"profiles/myprofile.html",context)

@login_required
def invities_recived_view(request):
    profile = Profile.objects.get(user=request.user)
    qs=Relationship.objects.invatations_recived(profile)
    results=list(map(lambda x:x.sender,qs))
    is_empty=False

    if len(results)==0:
        is_empty=True

    context={
        "qs":results,
        "is_empty":is_empty,
             }

    return render(request,"profiles/my_invities.html",context)


@login_required
def accept_invatation(request):
    if request.method=="POST":
        pk=request.POST.get("profile_pk")
        sender=Profile.objects.get(pk=pk)
        receiver=Profile.objects.get(user=request.user)
        rel=get_object_or_404(Relationship,sender=sender,reciver=receiver)
        if rel.status=="send":
            rel.status="accepted"
            rel.save()
    return redirect("profiles:my-invities-view")


@login_required
def reject_invatation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        receiver = Profile.objects.get(user=request.user)
        sender = Profile.objects.get(pk=pk)
        rel=get_object_or_404(Relationship,sender=sender,reciver=receiver)
        rel.delete()
    return redirect("profiles:my-invities-view")

@login_required
def invite_profiles_list_view(request):
    user=request.user
    qs=Profile.objects.get_all_to_invate(user)

    context={"qs":qs}

    return render(request,"profiles/to_invite_list.html",context)

@login_required
def profile_list_view(request):
    user=request.user
    qs=Profile.objects.get_all_profiles(user)

    context={"qs":qs}
    return render(request,"profiles/profile_list.html",context)





class ProfileDetailView(LoginRequiredMixin,DetailView):
    model = Profile
    template_name = "profiles/detail.html"

    def get_object(self, slug=None):
        slug=self.kwargs.get("slug")
        profile=Profile.objects.get(slug=slug)
        return profile


    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        user=User.objects.get(username__iexact=self.request.user)
        profile=Profile.objects.get(user=user)

        rel_r=Relationship.objects.filter(sender=profile)
        rel_s=Relationship.objects.filter(reciver=profile)

        rel_reciver=[]
        rel_sender=[]

        for item in rel_r:
            rel_reciver.append(item.reciver.user)

        for item in rel_s:
            rel_sender.append(item.sender.user)

        context["rel_receiver"]=rel_reciver
        context["rel_sender"] = rel_sender
        context["posts"]=self.get_object().get_all_authors_posts()
        context["len_posts"]=True if len(self.get_object().get_all_authors_posts()) > 0 else False
        return context






class ProfileListView(LoginRequiredMixin,ListView):
    model = Profile
    template_name = "profiles/profile_list.html"
    #context_object_name = "qs"

    def get_queryset(self):
        qs=Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        user=User.objects.get(username__iexact=self.request.user)
        profile=Profile.objects.get(user=user)

        rel_r=Relationship.objects.filter(sender=profile)
        rel_s=Relationship.objects.filter(reciver=profile)

        rel_reciver=[]
        rel_sender=[]

        for item in rel_r:
            rel_reciver.append(item.reciver.user)

        for item in rel_s:
            rel_sender.append(item.sender.user)

        context["rel_receiver"]=rel_reciver #rel_receiver Bu şekilde olması gerekiyor. yazarken e harfini yazmayı unutmuşum.
        context["rel_sender"] = rel_sender
        context["is_empty"] = False

        if len(self.get_queryset())==0:
            context["is_empty"]=True
        return context

@login_required
def send_invatation(request):
    if request.method=="POST":
        pk=request.POST.get("profile_pk")
        user=request.user
        sender=Profile.objects.get(user=user)
        receiver=Profile.objects.get(pk=pk)

        rel=Relationship.objects.create(sender=sender, reciver=receiver,status="send")

        return redirect(request.META.get("HTTP_REFERER"))

    return redirect("profiles:my-profile-view")

@login_required
def remove_from_friends(request):
    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(reciver=receiver)) | (Q(sender=receiver) & Q(reciver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')

profiles/templates/profiles/detail.html
{% extends 'base.html' %}

{% block title %}
profile detail
{% endblock title %}

{% block content %}
<div class="ui grid">
    <br>
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src={{object.avatar.url}}>
            <h1>{{object.user}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ object.get_post_no }}</div>
                </div>
                <div class="item">
                    Verilen Beğeni
                    <div class="ui label">{{ object.get_likes_given_no }}</div>
                </div>
                <div class="item">
                    Alınan Beğeni
                    <div class="ui label">{{ object.get_likes_recived_no }}</div>
                </div>
                <div class="item">
                    Arkadaşlar
                    <div class="ui label">{{ object.get_friends_no }}</div>
                </div>
            </div>

            {% if object.user not in rel_receiver and object.user not in rel_sender %}
                <form action="{% url 'profiles:send-invite-view' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Arkadaş Ekle</button>
                </form>
            {% endif %}

            {% if object.user in rel_receiver and request.user not in object.friends.all %}
                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>İstek Bekleniyor</button>
            {% endif %}

            {% if request.user in object.friends.all %}
                <form action="{% url 'profiles:remove-friend-view' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Arkadaşlıktan Çıkar</button>
                </form>
            {% endif %}

        </div>
        <div class="twelve wide column">
            {% if len_posts %}
                {% for post in posts %}
                    <div class="segment ui fluid">
                        {{post.content}}
                    </div>
                {% endfor %}
            {% else %}
                <h1>Bu kullanıcının hiç gönderisi yok ...</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

profiles/templates/profiles/my_invities.html
{% extends 'base.html' %}

{% block title %}
my invites
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>Hic istek yok..</h1>
    {% endif %}

    {% for obj in qs %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <br>
                        <a href="">
                            <button class="ui primary button w-big mb-5">Profili gör</button>
                        </a>
                        <form action="{% url 'profiles:accept-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui positive basic button w-big mb-5">
                                <i class="check icon"></i>
                                İsteği onayla
                            </button>
                        </form>
                         <form action="{% url 'profiles:reject-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button w-big mb-5">
                                <i class="close icon"></i>
                                İsteği redded
                            </button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}

{% block title %}
my profile
{% endblock title  %}

{% block content %}

    <div class="ui modal mymodal">
  <i class="close icon"></i>
  <div class="header">
    Profilini Güncelle
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src={{ profile.avatar.url }}>
    </div>
    <div class="description">
      <div class="ui header">hakkında bazı bilgiler.</div>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
    </div>
  </div>
  <div class="actions">

    <button type="submit" class="ui positive right labeled icon button">Update
        <i class="checkmark icon"></i>
    </button>
      </form>
  </div>
</div>




<div class="ui segment">
{% if confirm %}
    <div class="ui green message">Güncellendi</div>
{% endif %}
<h3>My profile: {{ profile.user }}</h3>
<div class="ui grid">
<div class="row">
    <div class="six wide column">
        <img class="ui medium rounded image" src="{{ profile.avatar.url }}" >
        <div class="row mt-5">
            <button class="ui secondary button" id="modal-btn">Profilini Güncelle</button>
        </div>
    </div>
    <div class="ten wide column">
      <table class="ui table">
          <tbody>
            <tr>
                <td>User Name</td>
                <td>{{ profile.user }}</td>
            </tr>

            <tr>
                <td>First Name</td>
                <td>{{ profile.first_name }}</td>
            </tr>

            <tr>
                <td>Last Name</td>
                <td>{{ profile.last_name }}</td>
            </tr>

            <tr>
                <td>Bio</td>
                <td>{{ profile.bio }}</td>
            </tr>

            <tr>
                <td>Arkadaş Sayısı</td>
                <td>{{ profile.get_friends_no }}</td>
            </tr>

          <tr>
                <td>Arkadaşlar</td>
                <td>
                    <ul>
                        {% for friend in profile.get_friends %}
                            <li>{{ friend }}</li>
                        {% endfor %}

                    </ul>
                </td>
            </tr>


          <tr>
                <td>Postların Sayısı</td>
                <td>{{ profile.get_post_no }}</td>
            </tr>

          <tr>
                <td>Like ların Sayısı</td>
                <td>{{ profile.get_likes_given_no }}</td>
            </tr>


          <tr>
                <td>Aldığımız Like ların Sayısı</td>
                <td>{{ profile.get_likes_recived_no }}</td>
            </tr>

          </tbody>
      </table>
    </div>
</div>

</div>



</div>









{% endblock content  %}

profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
    all profiles
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>Etkileşim içinde olan kullanıcı yok.</h1>
    {% endif %}

    {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>

                        <a href=""><button class="ui primary button mb-5 w-big">Profili Gör</button></a>
                        <br>

                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url 'profiles:send-invite-view' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Arkadaş Ekle</button>
                            </form>
                         {% endif %}

                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Onay Bekliyor</button>
                        {% endif %}

                        {% if request.user in obj.friends.all %}
                        <form action="{% url 'profiles:remove-friend-view' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Arkadaşlıktan Çıkar</button>
                        </form>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

profiles/templates/profiles/to_invite_list.html
{% extends 'base.html' %}

{% block title %}
    invite friends
{% endblock title %}


{% block content %}
    <ul>
        {% for item in qs %}
            <li>{{ item }}</li>
        {% endfor %}

    </ul>
{% endblock content %}